version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - sudo apt-get install graphviz
      - pip install poetry==1.3.2
      - poetry config virtualenvs.create false
      - poetry install -E airflow -E git -E s3 --with docs
