version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
  jobs:
    pre_install:
      - python -m pip install uv
      - uv export --extra git --extra s3 --group docs --format requirements.txt --no-hashes --output-file docs/requirements.txt

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
