version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install poetry==1.2.2
      - poetry config virtualenvs.create false
      - poetry install --with docs
